emf2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth import views as auth_views
#from rest_framework.urlpatterns import format_suffix_patterns
from microfinance import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^microfinance/', include('microfinance.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microfinance/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'microfinance'

urlpatterns = [

    # Administration
    url(r'^admin/', admin.site.urls),

    # Gestion
    url(r'^$', views.index, name='index'),
    url(r'^acceuil/$', views.acceuil, name='acceuil'),
    url(r'^déconnexion/$', views.logout_user, name='logout'),


    # Add, Update, Delete Agence URLS
    url(r'^agences/$', views.AgenceList.as_view(), name='agence_list'),
    url(r'^creer_agence/$', views.AgenceCreate.as_view(), name='agence_create'),
    url(r'^modifier_agence/(?P<pk>\d+)/$', views.AgenceUpdate.as_view(), name='agence_update'),
    url(r'^supprimer_agence/(?P<pk>\d+)/$', views.AgenceDelete.as_view(), name='agence_delete'),
    url(r'^detail_agence/(?P<pk>\d+)/$', views.AgenceDetailView.as_view(), name='detail_agence'),


    # Add, Update, Delete client URLS
    url(r'^clients/$', views.ClientList.as_view(), name='client_list'),
    url(r'^creer_client/$', views.ClientCreate.as_view(), name='client_create'),
    url(r'^modifier_client/(?P<pk>\d+)/$', views.ClientUpdate.as_view(), name='client_update'),
    url(r'^supprimer_client/(?P<pk>\d+)/$', views.ClientDelete.as_view(), name='client_delete'),
    url(r'^detail_client/(?P<pk>\d+)/$', views.ClientDetailView.as_view(), name='detail_client'),


    # Add, Update, Delete Type de Compte URLS
    url(r'^type_comptes/$', views.TypeCompteList.as_view(), name='typecompte_list'),
    url(r'^creer_type_compte/$', views.TypeCompteCreate.as_view(), name='typecompte_create'),
    url(r'^modifier_type_compte/(?P<pk>\d+)/$', views.TypeCompteUpdate.as_view(), name='typecompte_update'),
    url(r'^supprimer_type_compte/(?P<pk>\d+)/$', views.TypeCompteDelete.as_view(), name='typecompte_delete'),
    url(r'^detail_type_compte/(?P<pk>\d+)/$', views.TypeCompteDetailView.as_view(), name='detail_typecompte'),


    # Add, Update, Delete Type de Compte URLS
    url(r'^comptes/$', views.CompteList.as_view(), name='compte_list'),
    url(r'^creer_compte/$', views.CompteCreate.as_view(), name='compte_create'),
    url(r'^modifier_compte/(?P<pk>\d+)/$', views.CompteUpdate.as_view(), name='compte_update'),
    url(r'^supprimer_compte/(?P<pk>\d+)/$', views.CompteDelete.as_view(), name='compte_delete'),
    url(r'^detail_compte/(?P<pk>\d+)/$', views.CompteDetailView.as_view(), name='detail_compte'),


    # Add, Update, Delete Type de Personnel URLS
    url(r'^personnels/$', views.PersonnelList, name='personnel_list'),


    # Add, Update, Delete Type de Depot URLS
    url(r'^dépôts/$', views.DepotList.as_view(), name='depot_list'),
    url(r'^creer_dépôt/$', views.DepotCreate.as_view(), name='depot_create'),
    url(r'^modifier_dépôt/(?P<pk>\d+)/$', views.DepotUpdate.as_view(), name='depot_update'),
    url(r'^supprimer_dépôt/(?P<pk>\d+)/$', views.DepotDelete.as_view(), name='depot_delete'),
    url(r'^detail_dépôt/(?P<pk>\d+)/$', views.DepotDetailView.as_view(), name='detail_depot'),


    # Add, Update, Delete Type de Compte URLS
    url(r'^retraits/$', views.RetraitList.as_view(), name='retrait_list'),
    url(r'^creer_retrait/$', views.RetraitCreate.as_view(), name='retrait_create'),
    url(r'^modifier_retrait/(?P<pk>\d+)/$', views.RetraitUpdate.as_view(), name='retrait_update'),
    url(r'^supprimer_retrait/(?P<pk>\d+)/$', views.RetraitDelete.as_view(), name='retrait_delete'),
    url(r'^detail_retrait/(?P<pk>\d+)/$', views.RetraitDetailView.as_view(), name='detail_retrait'),



    

]

microfinance/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.forms import ModelForm
from .forms import UserForm, AgenceForm, ClientForm, TypeCompteForm, CompteForm, DepotForm, RetraitForm
import re
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Agence, Client, TypeCompte, Compte, Depot, Retrait
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your views here.



def index(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('microfinance:acceuil')
			else:
				return render(request, 'microfinance/index.html', {'error_message': 'Votre compte a été désactivé'})
		else:
			return render(request, 'microfinance/index.html', {'error_message': 'Paramètres Invalides'})
	return render(request, 'microfinance/index.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('microfinance:index')



def acceuil(request):
	agences_list = Agence.objects.count()
	clients_list = Client.objects.count()
	comptes_list = Compte.objects.count()
	depots_list = Depot.objects.count()
	retraits_list = Retrait.objects.count()
	users_list = User.objects.count()
	return render(request, 'microfinance/acceuil.html', {"agences": agences_list, "clients": clients_list, 
		"comptes": comptes_list, "depots": depots_list, "retraits": retraits_list, "users": users_list, })



# Agence CRUD

class AgenceList(ListView):
	model = Agence


class AgenceCreate(CreateView):
	model = Agence
	form_class = AgenceForm
	success_url = reverse_lazy('microfinance:agence_list')

class AgenceUpdate(UpdateView):
	model = Agence
	form_class = AgenceForm
	success_url = reverse_lazy('microfinance:agence_list')

class AgenceDelete(DeleteView):
	model = Agence
	success_url = reverse_lazy('microfinance:agence_list')

class AgenceDetailView(DetailView):

    model = Agence
    success_url = reverse_lazy('microfinance:agence_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



# Client CRUD

class ClientList(ListView):
	model = Client


class ClientCreate(CreateView):
	model = Client
	form_class = ClientForm
	success_url = reverse_lazy('microfinance:client_list')

class ClientUpdate(UpdateView):
	model = Client
	form_class = ClientForm
	success_url = reverse_lazy('microfinance:client_list')

class ClientDelete(DeleteView):
	model = Client
	success_url = reverse_lazy('microfinance:client_list')

class ClientDetailView(DetailView):

    model = Client
    success_url = reverse_lazy('microfinance:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



# TypeCompte CRUD

class TypeCompteList(ListView):
	model = TypeCompte


class TypeCompteCreate(CreateView):
	model = TypeCompte
	form_class = TypeCompteForm
	success_url = reverse_lazy('microfinance:typecompte_list')

class TypeCompteUpdate(UpdateView):
	model = TypeCompte
	form_class = TypeCompteForm
	success_url = reverse_lazy('microfinance:typecompte_list')

class TypeCompteDelete(DeleteView):
	model = TypeCompte
	success_url = reverse_lazy('microfinance:typecompte_list')

class TypeCompteDetailView(DetailView):

    model = TypeCompte
    success_url = reverse_lazy('microfinance:typecompte_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context




# Compte CRUD

class CompteList(ListView):
	model = Compte


class CompteCreate(CreateView):
	model = Compte
	form_class = CompteForm
	success_url = reverse_lazy('microfinance:compte_list')

class CompteUpdate(UpdateView):
	model = Compte
	form_class = CompteForm
	success_url = reverse_lazy('microfinance:compte_list')

class CompteDelete(DeleteView):
	model = Compte
	success_url = reverse_lazy('microfinance:compte_list')

class CompteDetailView(DetailView):

    model = Compte
    success_url = reverse_lazy('microfinance:compte_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# Personnel CRUD

class UsersView(TemplateView):
    template_name = 'microfinance/user_list.html'

    def get_context_data(self,**kwargs):
        context = super(UsersView,self).get_context_data(**kwargs)
        context['object_list'] = User.objects.all()
        return context


def PersonnelList(request):
	users_list = get_user_model().objects.all()
	return render(request, 'microfinance/personnel_list.html', {'users_list': users_list})



# Depot CRUD

class DepotList(ListView):
	model = Depot


class DepotCreate(CreateView):
	model = Depot
	form_class = DepotForm
	success_url = reverse_lazy('microfinance:depot_list')

class DepotUpdate(UpdateView):
	model = Depot
	form_class = DepotForm
	success_url = reverse_lazy('microfinance:depot_list')

class DepotDelete(DeleteView):
	model = Depot
	success_url = reverse_lazy('microfinance:depot_list')

class DepotDetailView(DetailView):

    model = Depot
    success_url = reverse_lazy('microfinance:depot_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# Retrait CRUD

class RetraitList(ListView):
	model = Retrait


class RetraitCreate(CreateView):
	model = Retrait
	form_class = RetraitForm
	success_url = reverse_lazy('microfinance:retrait_list')

class RetraitUpdate(UpdateView):
	model = Retrait
	form_class = RetraitForm
	success_url = reverse_lazy('microfinance:retrait_list')

class RetraitDelete(DeleteView):
	model = Retrait
	success_url = reverse_lazy('microfinance:retrait_list')

class RetraitDetailView(DetailView):

    model = Retrait
    success_url = reverse_lazy('microfinance:retrait_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

microfinance/templates/microfinance/agence_form.html
{% extends 'microfinance/base.html' %}

{% load staticfiles %}

{% load crispy_forms_tags %}

{% block title %}Créer une Agence{% endblock %}

{% block content %}

    

                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Créer une Agence</h4>
                                            <p class="text-muted m-b-30 font-14">Toute agence doit être ajouter ici par un membre du personnel ayant les accréditations.</p>

                                            {% crispy form %}

                                            
                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                        </div><!-- container-fluid -->





{% endblock %}

microfinance/templates/microfinance/agence_list.html
{% extends 'microfinance/base.html' %}



{% block title %}AGENCE{% endblock %}



{% block content %}


                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Liste des Agences</h4>
                                            <p class="text-muted m-b-30 font-14">
                                                Chaque agence doit être répertoriée dans le système.
                                            </p>

                                            <table id="datatable" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Nom</th>
                                                        <th>Email</th>
                                                        <th>Gérant</th>
                                                        <th>Code Pin</th>
                                                        <th>Actions</th>
                                                    </tr>
                                                </thead>


                                                <tbody>
                                                {% for agence in agence_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'microfinance:agence_update' agence.id %}">
                                                           {{ agence.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ agence.nomag }}</td>
                                                        <td>{{ agence.email }}</td>
                                                        <td>{{ agence.gerant }}</td>
                                                        <td>{{ agence.pincode }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'microfinance:agence_update' agence.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'microfinance:detail_agence' agence.id %}" class="btn btn-warning"><i class="fa fa-eye"></i></a>
                                                            <!--a href="{% url 'microfinance:agence_delete' agence.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a-->
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}
                                                
                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                            

                        </div>
                        <!-- container-fluid -->
							




{% endblock %}

microfinance/templates/microfinance/client_form.html
{% extends 'microfinance/base.html' %}

{% load staticfiles %}

{% load crispy_forms_tags %}

{% block title %}Ajouter un Client{% endblock %}

{% block content %}

    

                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Ajouter un Client</h4>
                                            <p class="text-muted m-b-30 font-14">Toute client doit être ajouter ici par un membre du personnel ayant les accréditations.</p>

                                            {% crispy form %}

                                            
                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                        </div><!-- container-fluid -->





{% endblock %}

microfinance/templates/microfinance/client_list.html
{% extends 'microfinance/base.html' %}



{% block title %}CLIENT{% endblock %}



{% block content %}


                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Liste des Clients</h4>
                                            <p class="text-muted m-b-30 font-14">
                                                Chaque client doit être répertoriée dans le système.
                                            </p>

                                            <table id="datatable" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Nom</th>
                                                        <th>Email</th>
                                                        <th>Agence</th>
                                                        <th>Code Pin Client</th>
                                                        <th>Actions</th>
                                                    </tr>
                                                </thead>


                                                <tbody>
                                                {% for client in client_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'microfinance:client_update' client.id %}">
                                                           {{ client.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ client.get_full_name }}</td>
                                                        <td>{{ client.email }}</td>
                                                        <td>{{ client.agence.pincode }}</td>
                                                        <td>{{ client.pincode }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'microfinance:client_update' client.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'microfinance:detail_client' client.id %}" class="btn btn-warning"><i class="fa fa-eye"></i></a>
                                                            <!--a href="{% url 'microfinance:client_delete' client.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a-->
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}
                                                
                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                            

                        </div>
                        <!-- container-fluid -->
							




{% endblock %}

microfinance/templates/microfinance/depot_form.html
{% extends 'microfinance/base.html' %}

{% load staticfiles %}

{% load crispy_forms_tags %}

{% block title %}Créer un Dépôt{% endblock %}

{% block content %}

    

                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Créer un Dépôt</h4>
                                            <p class="text-muted m-b-30 font-14">Tout dépôt doit être ajouter ici par un membre du personnel ayant les accréditations.</p>

                                            {% crispy form %}

                                            
                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                        </div><!-- container-fluid -->





{% endblock %}

microfinance/templates/microfinance/depot_list.html
{% extends 'microfinance/base.html' %}



{% block title %}DEPOTS{% endblock %}



{% block content %}


                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Liste des Dépôts</h4>
                                            <p class="text-muted m-b-30 font-14">
                                                Chaque dépôt doit être répertoriée dans le système.
                                            </p>

                                            <table id="datatable" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Agence</th>
                                                        <th>Client</th>
                                                        <th>Montant Déposé</th>
                                                        <th>Code Pin</th>
                                                        <th>Actions</th>
                                                    </tr>
                                                </thead>


                                                <tbody>
                                                {% for depot in depot_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'microfinance:depot_update' depot.id %}">
                                                           {{ depot.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ depot.agence }}</td>
                                                        <td>{{ depot.client }}</td>
                                                        <td>{{ depot.montantverse }}</td>
                                                        <td>{{ depot.pincode }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'microfinance:depot_update' depot.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'microfinance:detail_depot' depot.id %}" class="btn btn-warning"><i class="fa fa-eye"></i></a>
                                                            <!--a href="{% url 'microfinance:depot_delete' depot.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a-->
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}
                                                
                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                            

                        </div>
                        <!-- container-fluid -->
							




{% endblock %}

microfinance/templates/microfinance/retrait_form.html
{% extends 'microfinance/base.html' %}

{% load staticfiles %}

{% load crispy_forms_tags %}

{% block title %}Créer un Retrait{% endblock %}

{% block content %}

    

                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Créer un Retrait</h4>
                                            <p class="text-muted m-b-30 font-14">Tout retrait doit être ajouter ici par un membre du personnel ayant les accréditations.</p>

                                            {% crispy form %}

                                            
                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                        </div><!-- container-fluid -->





{% endblock %}

microfinance/templates/microfinance/typecompte_list.html
{% extends 'microfinance/base.html' %}



{% block title %}TYPE DE COMPTE{% endblock %}



{% block content %}


                        <div class="container-fluid">

                            <div class="row">
                                <div class="col-12">
                                    <div class="card m-b-20">
                                        <div class="card-body">

                                            <h4 class="mt-0 header-title">Liste des Types de Compte</h4>
                                            <p class="text-muted m-b-30 font-14">
                                                Chaque type de compte doit être répertoriée dans le système.
                                            </p>

                                            <table id="datatable" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Id</th>
                                                        <th>Libellé</th>
                                                        <th>Code Pin</th>
                                                        <th>Actions</th>
                                                    </tr>
                                                </thead>


                                                <tbody>
                                                {% for typecompte in typecompte_list %}
                                                      <tr>
                                                        <td>
                                                          <a href="{% url 'microfinance:typecompte_update' typecompte.id %}">
                                                           {{ typecompte.id }} 
                                                          </a>
                                                        </td>
                                                        <td>{{ typecompte.libelle }}</td>
                                                        <td>{{ typecompte.pincode }}</td>
                                                        <td>
                                                          <div class="btn-group" role="group" aria-label="...">
                                                            <a href="{% url 'microfinance:typecompte_update' typecompte.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                            <a href="{% url 'microfinance:detail_typecompte' typecompte.id %}" class="btn btn-warning"><i class="fa fa-eye"></i></a>
                                                            <!--a href="{% url 'microfinance:typecompte_delete' typecompte.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a-->
                                                          </div>
                                                        </td>
                                                      </tr>
                                                   {% endfor %}
                                                
                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div> <!-- end col -->
                            </div> <!-- end row -->

                            

                        </div>
                        <!-- container-fluid -->
							




{% endblock %}